// KYUB Feed Database - Rich pedagogical posts
const FEED_DATABASE = [
  { id: 'f-1', disciplineId: 'maths', type: 'daily_fact', title: '🔢 Le nombre d\'or', content: 'Le nombre d\'or (phi ≈ 1,618) se retrouve partout dans la nature : fleurs, coquillages et même dans les proportions du corps humain ! ✨', likes: 1240, saves: 450 },
  { id: 'f-2', disciplineId: 'physique', type: 'fiche', title: '🚀 Vitesse de libération', content: 'Pour quitter la Terre, une fusée doit atteindre 11,2 km/s. C\'est la vitesse nécessaire pour échapper à l\'attraction terrestre ! 🌍', likes: 890, saves: 320 },
  { id: 'f-3', disciplineId: 'svt', type: 'daily_fact', title: '🧬 ADN géant', content: 'Si on déroulait tout l\'ADN d\'une seule de tes cellules, il mesurerait 2 mètres de long. Multiplié par tes milliards de cellules, ça fait l\'aller-retour Terre-Pluton ! 🌌', likes: 2300, saves: 1100 },
  { id: 'f-4', disciplineId: 'histoire', type: 'fiche', title: '🏛️ La Pnyx', content: 'À Athènes, c\'est sur la colline de la Pnyx que les citoyens votaient les lois à main levée. La naissance de la démocratie ! 🗳️', likes: 560, saves: 180 },
  { id: 'f-5', disciplineId: 'ses', type: 'qcm_rapide', title: '📊 Test Éco', content: 'Si le prix d\'un produit augmente, que fait généralement la demande ?', question: { options: ['Elle augmente', 'Elle diminue', 'Elle reste stable', 'Elle disparaît'], correct: 1 }, likes: 450, saves: 90 },
  { id: 'f-6', disciplineId: 'anglais', type: 'daily_fact', title: '🇬🇧 False Friends', content: 'Attention ! "Actually" ne veut pas dire "Actuellement" mais "En fait". Pour dire actuellement, utilise "Currently" ! 💡', likes: 1100, saves: 540 },
  { id: 'f-7', disciplineId: 'chimie', type: 'fiche', title: '🧪 Le pH', content: 'Le pH mesure l\'acidité. < 7 c\'est acide (citron), > 7 c\'est basique (savon), et 7 c\'est neutre (eau pure) ! 💧', likes: 780, saves: 210 },
  { id: 'f-8', disciplineId: 'geo', type: 'daily_fact', title: '🌍 IDH', content: 'L\'IDH (Indice de Développement Humain) ne regarde pas que l\'argent, mais aussi l\'éducation et l\'espérance de vie. Le vrai progrès ! 📈', likes: 670, saves: 150 },
  { id: 'f-9', disciplineId: 'philo', type: 'daily_fact', title: '🪞 Allégorie de la Caverne', content: 'Platon imagine des prisonniers qui ne voient que des ombres. Pour lui, la philosophie, c\'est sortir voir le vrai soleil de la connaissance. ☀️', likes: 1500, saves: 700 },
  { id: 'f-10', disciplineId: 'nsi', type: 'fiche', title: '💻 Binaire', content: 'Les ordinateurs ne comprennent que le 0 et le 1. Pourquoi ? Parce que l\'électricité passe ou ne passe pas ! ⚡', likes: 920, saves: 400 },
  { id: 'f-11', disciplineId: 'espagnol', type: 'daily_fact', title: '🇪🇸 La ñ', content: 'La lettre "ñ" vient du Moyen Âge : les copistes écrivaient un petit "n" au-dessus d\'un grand pour gagner de la place ! ✍️', likes: 840, saves: 200 },
  { id: 'f-12', disciplineId: 'maths', type: 'fiche', title: '📐 Pythagore', content: 'Dans un triangle rectangle, le carré de l\'hypoténuse est égal à la somme des carrés des deux autres côtés. a² + b² = c² ! ✅', likes: 1100, saves: 300 },
  { id: 'f-13', disciplineId: 'physique', type: 'daily_fact', title: '⚡ Électricité', content: 'L\'électricité voyage presque à la vitesse de la lumière (300 000 km/s). C\'est pour ça que l\'ampoule s\'allume instantanément ! 💡', likes: 750, saves: 180 },
  { id: 'f-14', disciplineId: 'svt', type: 'fiche', title: '🍃 Photosynthèse', content: 'Les plantes transforment la lumière du soleil, l\'eau et le CO2 en sucre et en oxygène. Merci les plantes ! 🌳', likes: 1300, saves: 450 },
  { id: 'f-15', disciplineId: 'histoire', type: 'daily_fact', title: '📜 Édit de Caracalla', content: 'En 212, l\'empereur romain Caracalla donne la citoyenneté à tous les hommes libres de l\'Empire. Un tournant ! 🏛️', likes: 420, saves: 90 },
  { id: 'f-16', disciplineId: 'ses', type: 'fiche', title: '💰 Inflation', content: 'L\'inflation, c\'est quand les prix augmentent et que ton argent perd de sa valeur. On peut acheter moins de choses avec 1€. 📉', likes: 610, saves: 200 },
  { id: 'f-17', disciplineId: 'anglais', type: 'qcm_rapide', title: '🇬🇧 Grammar Check', content: 'Which sentence is correct?', question: { options: ['I have 15 years', 'I am 15 years old', 'I has 15 years', 'I am 15 year'], correct: 1 }, likes: 980, saves: 300 },
  { id: 'f-18', disciplineId: 'chimie', type: 'daily_fact', title: '💎 Diamant vs Mine', content: 'Le diamant et la mine de ton crayon (graphite) sont faits du même atome : le Carbone. Seule la structure change ! ✏️', likes: 1900, saves: 800 },
  { id: 'f-19', disciplineId: 'geo', type: 'fiche', title: '🏙️ Mégalopole', content: 'Une mégalopole est une immense région urbaine qui relie plusieurs métropoles entre elles (ex: Boston à Washington). 🚄', likes: 530, saves: 120 },
  { id: 'f-20', disciplineId: 'nsi', type: 'daily_fact', title: '💾 Premier Bug', content: 'Le mot "bug" vient d\'un vrai insecte (une mite) qui s\'était coincé dans un ordinateur en 1947 ! 🦋', likes: 1400, saves: 600 }
];
